import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import BottomNavbar from "./components/BottomNavbar";

const poppins = Poppins({ subsets: ["latin"], weight:"400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${process.env.NODE_ENV === 'development' ? 'debug-screens' : "" } ${poppins.className}`} >
      {/* <Navbar/> */}
        {children}
        </body>
    </html>
  );
}
