import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import FooterSection from "./components/FooterSection";

const poppins = Poppins({ subsets: ["latin"],  weight: ['300','400','500','600', '700','800','900'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${process.env.NODE_ENV === 'development' ? 'debug-screens' : "" } ${poppins.className}`} >
      <Navbar/>
        {children}
        <FooterSection/>
        </body>
    </html>
  );
}
